#!/usr/bin/env bash
#Script installs Nginx server,redirects /redirect_me and customizes 404 error
apt-get -y update
apt-get -y install nginx
echo "4-not_found_page_404" > /var/www/html/index.nginx-derbian.html
echo "Ceci n'est pas une page" > /usr/share/nginx/html/custom_404.html
sed -i "s/server_name_;/server_name_;\n\trewrite ^\/redirect_me
https:\/\/github.com\/manlebza permanent;\n\n\terror_page 404\/
custom_404.html;\n\tlocation = \/custom_404.html {\n\t\troot\/
usr\/share\/nginx\/html;\n\t\tinternal;\n\t}"
/etc/nginx/sites-available/default
service nginx start
