#!/usr/bin/env bash
#This script configures the Nginx server with custom header
apt-get -y update
sudo apt-get -y install nginx
echo "alx-hbtn School" > /var/www/html/index.nginx-derbian.html
echo "Ceci n'est pas une page" > /usr/share/nginx/html/custom_404.html
sed -i "s/server_name_;/server_name;\n\trewrite ^\/redirect_me
https:\/\/github.com\/manlebza permanent;\n\n\terror_page 404\/custom_404.html;
\n\tlocation= \/custom_404.html {\n\t\troot\/usr\/share\/nginx\/html;
\n\t\tinternal;\n\t}/" /etc/nginx/sites-available/default
sed -i "s/include \/etc\/nginx\/sites-enabled\/\*;
/include\/etc\/nginx\/sites-enabled\/\*;
\n\tadd_header X-Served-By \"$HOSTNAME\";/" /etc/nginx/nginx.conf
service nginx start
