#!/usr/bin/env bash
#Creates a script that uses if, else if and else statement
x=1
while [ $x -le 10 ]
do
	if [ $x -eq 4 ]
	then
		echo "bad luck"
	elif [ $x -eq 8 ]
	then
		echo "good luck"
	else
		echo "Best school"
	fi
	((x++))
done
