#!/usr/bin/env bash
# This script starts the nginx as nginx user
sudo chmod 777 /etc/nginx/nginx.conf
chown nginx:nginx /etc/nginx/nginx.conf
sudo sed -i "s/80/8080/g" /etc/nginx/sites-available/default
pkill -9 apache
su nginx -c "service nginx restart"
